parameters:
#    manatee_core.example.class: Manatee\CoreBundle\Example


services:
    manatee_core.api_key_user_provider:
        class: Manatee\CoreBundle\Security\ApiKeyUserProvider
        arguments: [ @doctrine ]

    manatee_core.api_key_authenticator:
        class: Manatee\CoreBundle\Security\ApiKeyAuthenticator
        arguments: ["@manatee_core.api_key_user_provider"]